import "dotenv/config";

interface Config {
  LOCAL_PORTAL_DOMAIN: string;
  LOCAL_PORTAL_EMAIL: string;
  LOCAL_PORTAL_PASSWORD: string;
  K6_INFLUXDB_ORGANIZATION: string;
  K6_INFLUXDB_BUCKET: string;
  K6_INFLUXDB_TOKEN: string;
  K6_INFLUXDB_ADDR: string;
  K6_ELASTICSEARCH_CLOUD_ID: string;
  K6_ELASTICSEARCH_USER: string;
  K6_ELASTICSEARCH_PASSWORD: string;
  K6_PROMETHEUS_RW_SERVER_URL: string;
  K6_PROMETHEUS_RW_USERNAME: string;
  K6_PROMETHEUS_RW_PASSWORD: string;
}

const config: Config = {
  LOCAL_PORTAL_DOMAIN: process.env.LOCAL_PORTAL_DOMAIN ?? "",
  LOCAL_PORTAL_EMAIL: process.env.LOCAL_PORTAL_EMAIL ?? "",
  LOCAL_PORTAL_PASSWORD: process.env.LOCAL_PORTAL_PASSWORD ?? "",
  K6_INFLUXDB_ORGANIZATION: process.env.K6_INFLUXDB_ORGANIZATION ?? "",
  K6_INFLUXDB_BUCKET: process.env.K6_INFLUXDB_BUCKET ?? "",
  K6_INFLUXDB_TOKEN: process.env.K6_INFLUXDB_TOKEN ?? "",
  K6_INFLUXDB_ADDR: process.env.K6_INFLUXDB_ADDR ?? "",
  K6_ELASTICSEARCH_CLOUD_ID: process.env.K6_ELASTICSEARCH_CLOUD_ID ?? "",
  K6_ELASTICSEARCH_USER: process.env.K6_ELASTICSEARCH_USER ?? "",
  K6_ELASTICSEARCH_PASSWORD: process.env.K6_ELASTICSEARCH_PASSWORD ?? "",
  K6_PROMETHEUS_RW_SERVER_URL: process.env.K6_PROMETHEUS_RW_SERVER_URL ?? "",
  K6_PROMETHEUS_RW_USERNAME: process.env.K6_PROMETHEUS_RW_USERNAME ?? "",
  K6_PROMETHEUS_RW_PASSWORD: process.env.K6_PROMETHEUS_RW_PASSWORD ?? "",
};

export default config;
