input {
    beats {
        port => "5044"
    }
}
filter {
    if( [tags][0] == "sql" ) {
        csv {
	        separator => "|"
			columns => ["Time", "ThreadId", "Elapsed", "Command", "Parametrs"]
	    }
		mutate {
            convert => {
               "Elapsed" => "integer"
			}
        }
	    date {
            match => ["Time", "yyyy-MM-dd HH:mm:ss,SSS"]
		    timezone => "UTC"
		    target => "created"
        }
	}
	else if( [tags][0] == "logs" ) {
	    csv {
	        separator => "|"
			columns => ["Time", "Level", "ThreadId", "Message", "Exception"]
	    }
	    date {
            match => ["Time", "yyyy-MM-dd HH:mm:ss,SSS"]
		    target => "created"
        }
	}
	else if( [tags][0] == "asp" ) {
	    csv {
	        separator => "|"
			columns => ["Time", "EventId", "Level", "Logger", "Message", "URL", "Action"]
	    }
	    date {
            match => ["Time", "yyyy-MM-dd HH:mm:ss,SSS"]
		    target => "created"
        }
	}
}
output {
    if( [tags][0] == "sql" ) {
        elasticsearch {
	        index => "docspace-sql-%{+YYYY.MM.dd}" 
            hosts => [ "localhost:9200" ]
        }
    }
	else if( [tags][0] == "logs" ) {
        elasticsearch {
		    index => "docspace-logs-%{+YYYY.MM.dd}"
            hosts => ["localhost:9200"]
        }
    }
	else if( [tags][0] == "asp" ) {
        elasticsearch {
		    index => "docspace-asp-%{+YYYY.MM.dd}"
            hosts => ["localhost:9200"]
        }
    }
}